version: '3.8'

services:
    db:
        image: postgres
        restart: always
        environment:
            - POSTGRES_USER=postgres
            - POSTGRES_PASSWORD=postgres
            - POSTGRES_DB=test
            - "POSTGRES_HOST_AUTH_METHOD=trust"
        ports:
            - "5430:5432" 
        volumes:
            - ./db_data:/var/lib/postgresql/data
        networks: 
            - php_postgres

    adminer:
        build: 
            context: .
            dockerfile: Dockerfile.adminer
        ports: 
            - 8082:8082
        volumes: 
            - ./adminer:/var/www/html
        networks: 
            - php_postgres

networks:
    php_postgres:
        driver: bridge
