FROM alpine:latest


RUN apk add sudo
RUN apk update && apk --no-cache add postgresql
RUN echo 'postgres ALL=(ALL) NOPASSWD:ALL' >> /etc/sudoers
USER postgres

ENV PGDATA=/var/lib/postgresql/data

RUN sudo mkdir -p "$PGDATA"


COPY postgresql.conf "$PGDATA/postgresql.conf"
# RUN chown postgres:postgres "$PGDATA/postgresql.conf" && chmod 600 "$PGDATA/postgresql.conf"
RUN sudo chown -R postgres:postgres /var/lib/postgresql/data
EXPOSE 5432

CMD ["postgres"]