version: '3.8'


services:
    app:
        build:
            args:
                user: root
                uid: 0
            context: .
            dockerfile: Dockerfile.php
        restart: unless-stopped
        working_dir: /var/www/
        volumes:
            - ./app:/var/www
        networks:
            - challenge
    
    nginx:
        image: nginx:alpine
        restart: unless-stopped
        ports:
            - 80:80
        volumes:
            - ./app:/var/www
            - ./conf:/etc/nginx/conf.d/
        networks:
            - challenge    
      
    composer:
        build:
            context: .
            dockerfile: Dockerfile.composer
        volumes:
            - ./app:/app
        working_dir: /app
        depends_on:
            - app

    postgres:
        image: postgres
        restart: always
        environment:
            - POSTGRES_USER=postgres
            - POSTGRES_PASSWORD=postgres
            - POSTGRES_DB=test
            - "POSTGRES_HOST_AUTH_METHOD=trust"
        ports:
            - "5430:5432" 
        volumes:
            - ./db_data:/var/lib/postgresql/data
        networks: 
            - challenge
        
    adminer:
        build: 
            context: .
            dockerfile: Dockerfile.adminer
        ports: 
            - 8082:8082
        volumes: 
            - ./adminer:/var/www/html
            

networks:
    challenge:
        driver: bridge