version: '3.8'

services:
    php:
        build:
            context: .
            dockerfile: Dockerfile.php
        volumes:
            - ./app:/var/www/html
        depends_on:
            - db
        networks: 
            - php_postgres

    db:
        extends:
            file: docker-compose-postgres.yml
            service: db

    nginx:
        image: nginx:latest
        ports:
            - 80:80
        volumes:
            - ./app:/var/www/html
        depends_on:
            - php
      
    composer:
        build:
            context: .
            dockerfile: Dockerfile.composer
        volumes:
            - ./app:/app
        working_dir: /app
        depends_on:
            - php
            

networks:
    php_postgres:
        external: true